include $(BASE_DIR)/Header.mk

MODULE  := silentDreamFw
SRC_DIR :=
DEFINE  :=
INCLUDE :=
LDFLAGS := 
LIBS    := -pthread -lunwind


$(call build-target, shared_library)

include $(BASE_DIR)/Footer.mk

